# Generated by Django 5.0.1 on 2024-01-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logixName', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
            ],
        ),
    ]
